USE [tallercuero]
GO
CREATE LOGIN [resventa1] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


CREATE LOGIN [resventa2] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE LOGIN [Vendedor1] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [Vendedor2] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


CREATE LOGIN [Vendedor3] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [Vendedor4] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [Caja1] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

CREATE LOGIN [Caja2] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [Bodega1] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE LOGIN [Gerente] WITH PASSWORD=N'1234', DEFAULT_DATABASE=[tallercuero], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

